name: teemo_professor
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.6+4
  flutter_modular: ^5.0.3
  flutter_screenutil: ^5.6.0
  mobx: ^2.1.1

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.7+3
  integration_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - lib/assets/images/
    # - lib/assets/images/error.image.png
    # - lib/assets/images/teemo_loading.gif
    # - lib/assets/images/baron-icon.png
    # - lib/assets/images/dragon-icon.png
    # - lib/assets/images/rift-herald-icon.png

  fonts:
    - family: TeemoFont1
      fonts:
        - asset: lib/assets/fonts/TeemoFont1-Bold.ttf
        - asset: lib/assets/fonts/TeemoFont1-BoldItalic.ttf
        - asset: lib/assets/fonts/TeemoFont1-Italic.ttf
        - asset: lib/assets/fonts/TeemoFont1-Light.ttf
        - asset: lib/assets/fonts/TeemoFont1-LightItalic.ttf
        - asset: lib/assets/fonts/TeemoFont1-Medium.ttf
        - asset: lib/assets/fonts/TeemoFont1-MediumItalic.ttf
        - asset: lib/assets/fonts/TeemoFont1-Regular.ttf
        - asset: lib/assets/fonts/TeemoFont1-SemiBold.ttf
        - asset: lib/assets/fonts/TeemoFont1-SemiBoldItalic.ttf
    - family: TeemoFont2
      fonts:
        - asset: lib/assets/fonts/TeemoFont2-Bold.ttf
        - asset: lib/assets/fonts/TeemoFont2-Light.ttf
        - asset: lib/assets/fonts/TeemoFont2-Medium.ttf
        - asset: lib/assets/fonts/TeemoFont2-Regular.ttf
        - asset: lib/assets/fonts/TeemoFont2-SemiBold.ttf


