// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqi4uDNl1j2K6XfidQYnvxYTQze9z6bZA',
    appId: '1:1014512831598:web:714fdd7bf8f4603bce2a7f',
    messagingSenderId: '1014512831598',
    projectId: 'professor-teemo',
    authDomain: 'professor-teemo.firebaseapp.com',
    storageBucket: 'professor-teemo.appspot.com',
    measurementId: 'G-TPWVFZY6BG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9GdV6MxHU7JPYxL-IRqT8uRqN9uZ7qcU',
    appId: '1:1014512831598:android:a7912c81fbe925b8ce2a7f',
    messagingSenderId: '1014512831598',
    projectId: 'professor-teemo',
    storageBucket: 'professor-teemo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEFUKudLvEFGfniKT89R25Em7ih2rA9CE',
    appId: '1:1014512831598:ios:0c50b60ba5d1b6dece2a7f',
    messagingSenderId: '1014512831598',
    projectId: 'professor-teemo',
    storageBucket: 'professor-teemo.appspot.com',
    iosClientId: '1014512831598-g5td965pkt4pljv53foenda3f9ts5h08.apps.googleusercontent.com',
    iosBundleId: 'com.example.teemoProfessor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEFUKudLvEFGfniKT89R25Em7ih2rA9CE',
    appId: '1:1014512831598:ios:0c50b60ba5d1b6dece2a7f',
    messagingSenderId: '1014512831598',
    projectId: 'professor-teemo',
    storageBucket: 'professor-teemo.appspot.com',
    iosClientId: '1014512831598-g5td965pkt4pljv53foenda3f9ts5h08.apps.googleusercontent.com',
    iosBundleId: 'com.example.teemoProfessor',
  );
}
